<!DOCTYPE html>
<html>
<head>
    <title>Remove item</title>
</head>
<body>
<?php
if ($_GET["success"] == "yes")
	echo '<script>alert("Item successfully deleted");</script>';
elseif ($_GET["success"] == "no")
	echo '<script>alert("ERROR: Item does not exist");</script>';
?>
    <h1>Remove item:</h1>
    <form action="delete_item.php" method="post">
        Item name:      <input type="text" name="name" placeholder="Name" value="" required>
        <button type="submit" name="submit" value="Delete">Delete</button>
    </form>
</body>
</html>