<!DOCTYPE html>
<html>
<head>
    <title>Log in</title>
</head>
<body>

    <h1>Log in:</h1>

    <form action="login.php" method="post">
        User name: <input type="text" name="login" placeholder="Login" value="">
        <br><br>
        Password:  <input type="password" name="passwd" placeholder="Password" value="">
        <br><br>
        <button type="submit" name="submit" value="OK">LOGIN</button>
    </form>

</body>
</html>